version: '3'
services:
  samba:
    image: dperson/samba
    container_name: samba-server
    restart: unless-stopped
    ports:
      - "139:139"
      - "1445:445"
    volumes:
      - ./server:/samba/share
    command: '-s "shared;/samba/share;yes;no;yes"'
